### ISSUE TITLE
Using the same separator in indy namespace and after is confusing

### ISSUE THREAD

**Issue by ekr** [hyperledger/indy-did-method#22]
As I understand S 11 you use the same separator inside the indy namespace as after it. I.e., you have the following ABNF
(I have slightly modified it to make this point).

```
did-indy := "did" ":" "indy" ":" ns ":" NSIDstring
ns     = namestring (":" namestring)
```

This seems non-ideal because at the point where you reach the fourth colon-separated value you do not know whether it is a subspace or an NSIDstring. You can't even tell by parsing the third component because you could have namespace = "sovrin" or "sovrin:staging". This seems like a likely source of bugs. It would be better if the interior separator were not a colon.

I recognize that we are a little short on characters here, but how about using period instead.

```
ns     = namestring ("." namestring)
```
This seems like it is permitted by the DID ABNF and is non-disruptive as namestring already forbids ".".

**Comment by swcurran** [comment]
Excellent idea.  I think we spent a bunch of time talking about the form of the namespace (human readable or not, handling non-production but related spaces and so on) that we didn't think about all the ":"s and what else we could do.  Since this is still a draft, I think adding in a PR for this would be a good idea.

Happy if you want to, or I will create one.

**Comment by ekr** [comment]
Go for it. I'm not sure I'll find all the places to fix

**Comment by paulbastian** [comment]
Although it is technically pretty easy to parse this structure with a regex, I see the advantages, as its better readable for humans. Are there any similarities from other DID Methods? I would agree to the change otherwise

**Comment by dbluhm** [comment]
I'm not personally strongly opinionated about this change but I do want to call out that many other DID methods currently do follow the conventions of `did:method:network:method-specific-id`. See https://dev.uniresolver.io/ in the examples dropdown for a quick sampling of a few different DIDs following that convention. @ekr makes a strong point for diverge from this convention but I think there's something to be said for adhering to it as well.

**Comment by swcurran** [comment]
After discussing this on the Indy Contributors call today (2022.02.01) we've decided that the common practice with other DID Methods is to use the ":" for this purpose and rather than pushing back against that convention and use a ".", we're going to stay with the ":" for the did:indy DID Method.

Per @peacekeeper, quoting from the DID Spec. that suggests ":"s are the way to go.

> The meaning of colons in the method-specific-id is entirely method-specific. Colons might be used by DID methods for establishing hierarchically partitioned namespaces, for identifying specific instances or parts of the verifiable data registry, or for other purposes. Implementers are advised to avoid assuming any meanings or behaviors associated with a colon that are generically applicable to all DID methods. 

Closing this issue and the related PR that was submitted.
