### ISSUE TITLE
Use of verkey

### ISSUE THREAD

**Issue by ekr** [hyperledger/indy-did-method#23]
I'm trying to wrap my head around the did:indy security properties.

As I understand it, on initial write, the namespace component needs to
be derived from the verkey, so for instance, we might have:

   verkey = 12345...ab
   did = did:indy:sovrin:12345...

On write, I am required to sign the transaction. The text is somewhat
unclear about what this means, but I assume that the transaction is an
Indy concept and so the signature doesn't get carried around.  And the
ledger is required to verify the signature, so it should be
consistent.

However, if I *update* the entry, as in 10.2, I can update the verkey,
which requires a signature by both the old and new verkeys.

   The NYM transaction requires that the transaction to be written is
   signed by the DID controller using the existing verkey and, if a
   new verkey is being provided, the new verkey. The ledger MUST
   verify the signature(s). If the signature(s) cannot be validated,
   the transaction MUST be rejected and an error returned to the
   client.

But at this point, the id will no longer match the verkey unless
I get fantastically lucky (or unlucky, I guess). Am I right so far?
This seems consistent with the fact that that on reading you don't
seem to be required to verify a signature or check that the verkey
matches the namespace component. I see that step 5 requires verifying
the state proof but if I understand correctly, that just checks the
ledger itself, not a signature chain from the original verkey.

Is this correct?

**Comment by swcurran** [comment]
The purpose of the DID is to have a stable identifier with a related public key that can be rotated.

The idea that we are trying to get across, but seems not to be clear is this:

1. When I create a DID, it's identifier is derived from the initial verkey (as you indicate). So if verkey is VK, then DID=F(VK), and anyone can confirm that.
2. When you want to rotate the key (change the verkey), the transaction is signed by the old and new private keys, and those signatures are verified. This creates a new ledger entry with the same DID as the initial entry, but a new verkey.

When you come across a key where the DID <> F(VK), then you can look at previous NYM ledger entries for that DID to trace back such that at some point the DID = F(VK) (the initial DID), and based on the ledger rules, know that all updates to that NYM were signed by a party that had access to the old and new private keys.

If the current private key is compromised by a malicious actor, control of the DID can be taken over by that entity. Responsibility for that is on the controller of the DID.

Hopefully that answers your question.

Going a bit further:

We realize that this is not as secure an approach as KERI uses, where an identifier always has both a current and next VerKey stored with the identifier, and a rotation can ONLY be done to the "next verkey", via a signed transaction with the related private key.   The benefit of that approach is that if the current private key of the controller is compromised, control over the identifier can be retrieved by submitting a transaction signed by the private key for the "next" verkey. The practice behind this is the idea that the controller keeps the "current" private key accessible so it can be used, and keeps the "next" private key offline so that the two can't be compromised together.  Of course, if they both are compromised at the same time, you are, as they say, hooped.

**Comment by ekr** [comment]
> When you come across a key where the DID <> F(VK), then you can look at previous NYM ledger entries for that DID to trace back such that at some point the DID = F(VK) (the initial DID), and based on the ledger rules, know that all updates to that NYM were signed by a party that had access to the old and new private keys.
 
But this is not directly verifiable, correct? I.e., I am just trusting the ledger to enforce those rules. And in fact, I don't know that the creator of the did *ever* had the private key because only the ledger verified it.

As I read VerKey and KERI, the relying party can actually verify the key rotation but not here. Is that correct?

**Comment by swcurran** [comment]
That should be possible.  I was looking at indyscan.io as I was writing the previous note and expecting to be able to see the signatures, but didn't, so AFAIK today, it is not verifiable. You are right, the sequence of DIDs should be verifiable and I'll add a note to the spec. to see if the implementation can support that.

**Comment by swcurran** [comment]
OK -- did some more checking.  The signature is available from the ledger and so can be verified -- see this: https://indyscan.io/tx/SOVRIN_MAINNET/domain/78559, scrolling down to the "Original Ledger Data" section.

**Comment by ekr** [comment]
Great. Should the spec require that you check it and describe how to do so?

**Comment by swcurran** [comment]
It should definitely describe how to do it, and the ledger should have functionality to make it easy.

A MUST (in the context of the specification) for a client doing the verification is probably not viable -- I don't think the spec can force someone to do something that they may not feel is needed.  But we definitely want to make it easy.

**Comment by ekr** [comment]
Well, the spec can't force someone to do something (there are no protocol police), but it's pretty common for security protocol specifications to require behavior that is necessary for security. For instance, here are some MUSTs from QUIC:

```
  A receiver MUST close the connection with an error of type
   FLOW_CONTROL_ERROR if the sender violates the advertised connection
   or stream data limits; see Section 11 for details on error handling.
```

```
   The values provided by a peer for these transport parameters MUST
   match the values that an endpoint used in the Destination and Source
   Connection ID fields of Initial packets that it sent (and received,
   for servers).  Endpoints MUST validate that received transport
   parameters match received connection ID values.
```

At the bare minimum the Security Considerations should make clear what the implications of failure to do so are.

**Comment by swcurran** [comment]
Agreed.  I'm not saying we shouldn't tell people to do it. Just questioning if a MUST is permitted for an operation done by a client.  But if there is a spec. convention on that -- happy to do it.  Definitely want it in the security considerations.

I think the most important thing at this point is in the updates to Indy Node to do this, we had a way to make it easy to collect all the signatures to enable the verification. For example, we could add to the transaction recorded on the ledger the sequence number of the previous NYM, so that the client can easily "walk the chain".

**Comment by ekr** [comment]
I think whether it's permitted is probably dependent on the SDO. It would
be permitted (and common) at IETF and W3C.

**Comment by swcurran** [comment]
We need to sort out the question of "do we need the transaction signed by the old and new key?". Should we remove that?  If so, we need a PR - nudge, nudge.

AFAIK with KERI, there an identifier is created with two public keys, the current one and the "pre-rotated" one such that the DID controller can restore control of their DID should their current private key be compromised. The assumes that the "pre-rotated" private key *cannot* be compromised (or at least, it is very, very unlikely because of how it is managed).

In the "Future Considerations" section, we talk about multi-sig NYMs, but that's not a now thing -- nor is the KERI extra "pre-rotated" verkey.

**Comment by paulbastian** [comment]
My argument is: we don't gain anything by requiring an additional signature with the new key, so we shouldn't change the current implementation

**Comment by swcurran** [comment]
Sounds good.  I'll do a PR for that.

**Comment by swcurran** [comment]
We need to address that the client SHOULD walk the trail of NYMs to verify self-certification. That goes back to the question of whether there is a way to query the sequence of NYM update transaction via a series of ledger calls.  AFAIK, there is not today and it's not clear it could be easily added.  Of course, it could be checked via a download of the transactions, such as with indyscan.io.
